#Cấu hình Prometheus

global:
  scrape_interval: 10s #cứ 10s sẽ gửi request đến các service để ấy data
  evaluation_interval: 10s

scrape_configs:
  # Chính nó (Prometheus)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  #IAM Service
  - job_name: 'iam-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']

  #API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000']

  #Storage Service
  - job_name: 'storage-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8088']